'use client';
import {createContext,useContext,useEffect,useRef,useState,type FormEvent} from 'react';
import {validateResponse} from '@/lib/rsvp/validation.mjs';
import './rsvp-feedback.css';
export const InvitationToken=createContext('');
type Invitation={main_guest_name:string;reserved_seats:number;attendance:string|null;additional_names:string[];message:string;submitted_at:string|null};
export function HouseholdRSVP(){
 const errorDialog=useRef<HTMLDialogElement>(null);
 const formRef=useRef<HTMLFormElement>(null);
 const returnFocus=useRef<HTMLElement|null>(null);
 function dismissError(){
   errorDialog.current?.close();
   const field= /guest|name|seat|additional|number/i.test(error) ? formRef.current?.querySelector<HTMLInputElement>('input[name="additionalNames"]') : /attendance|attend|declin/i.test(error) ? formRef.current?.querySelector<HTMLInputElement>('input[name="attendance"]') : null;
   setError('');
   (field || returnFocus.current)?.focus();
 }
 const [retry,setRetry]=useState(0);const token=useContext(InvitationToken);const [invitation,setInvitation]=useState<Invitation|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [attendance,setAttendance]=useState('');const [names,setNames]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{
   if(!error || !invitation || invitation.submitted_at)return;
   returnFocus.current=document.activeElement as HTMLElement;
   errorDialog.current?.showModal();
 },[error,invitation]);
 useEffect(()=>{if(!token)return;let active=true;fetch('/api/invitations/'+encodeURIComponent(token)).then(async r=>{const data=await r.json() as Invitation & {error:string};if(!r.ok)throw Error(data.error);if(active)setInvitation(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[token,retry]);
 async function submit(e:FormEvent){e.preventDefault();if(!invitation||busy)return;setError('');try{validateResponse({attendance,additionalNames:names,message},invitation.reserved_seats);}catch(e){setError((e as Error).message);return;}setBusy(true);try{const r=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,attendance,additionalNames:names,message})});const data=await r.json() as {error:string};if(!r.ok)throw Error(data.error);setInvitation({...invitation,attendance,additional_names:attendance==='attending'?names.split(',').map(n=>n.trim()).filter(Boolean):[],message,submitted_at:new Date().toISOString()});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="rsvp-panel"><h2>{invitation ? `${invitation.main_guest_name}, will you join us?` : "Will you join us?"}</h2><p className="rsvp-welcome">{invitation ? <>Our day would be sweeter with you there! We’ve saved <strong>{invitation.reserved_seats} {invitation.reserved_seats===1?"seat just for you":"seats for you and your guests"}</strong>. Come celebrate, laugh, and make memories with us.</> : "We would be delighted to have you."}</p>{!token?<p>Please open your personal invitation link to RSVP. Contact Clive and Rubie if you need your link.</p>:!invitation?<div><p role="status">{error||'Opening your invitation…'}</p>{error&&<button type="button" className="button" onClick={()=>{setError('');setRetry(value=>value+1);}}>Try again</button>}</div>:invitation.submitted_at?<div role="status"><h3>Thank you, {invitation.main_guest_name}.</h3><p>Your response has been received: {invitation.attendance==='attending'?'Attending':'Declining'}.</p>{invitation.attendance==='attending'&&<p>{[invitation.main_guest_name,...invitation.additional_names].join(', ')}</p>}{invitation.message&&<blockquote>{invitation.message}</blockquote>}<p>Please contact Clive and Rubie personally for any changes.</p></div>:<form ref={formRef} noValidate onSubmit={submit}><fieldset className="attendance"><legend>Will you attend?</legend>{['attending','declining'].map(value=><label key={value}><input type="radio" name="attendance" required value={value} checked={attendance===value} onChange={()=>setAttendance(value)}/>{value==='attending'?'Attending':'Declining'}</label>)}</fieldset>{attendance==='attending'&&invitation.reserved_seats>1&&<label className="message-field">Additional guest names (optional)<input name="additionalNames" value={names} onChange={e=>setNames(e.target.value)} maxLength={2000} placeholder="Example: Akali, Evelynn" aria-describedby="guest-help"/><span id="guest-help">Up to {invitation.reserved_seats-1} additional guests. Separate names with commas; leave blank if attending alone.</span></label>}<label className="message-field">A message for the couple (optional)<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000}/></label><div className="rsvp-actions"><p className="form-note">Please check your names before submitting. Contact us personally for any later changes.</p><button className="button" disabled={busy}>{busy?'Sending…':'Send RSVP'}</button></div></form>}<dialog ref={errorDialog} className="rsvp-feedback-dialog" aria-labelledby="rsvp-error-heading" aria-describedby="rsvp-error-description" onCancel={event=>{event.preventDefault();dismissError();}}><h3 id="rsvp-error-heading">Let’s check your response</h3><p id="rsvp-error-description">{error}</p><button type="button" className="button" onClick={dismissError} autoFocus>Got it</button></dialog></div>;
}
