'use client';
import { useRef,useState,type FormEvent } from 'react';
import { ArrowUpRight,Check,Heart } from 'lucide-react';
import { toast } from 'sonner';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { weddingData } from '@/lib/wedding-data';
export function RSVPSection(){const [attendance,setAttendance]=useState('attending');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState('');const id=useRef('');
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');id.current ||= crypto.randomUUID();try{const res=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),attendance,dietary:attendance==='attending'?form.get('dietary')||'':'',song:attendance==='attending'?form.get('song')||'':'',requestId:id.current})});if(!res.ok){const data=await res.json() as {error?:string};throw new Error(data.error||'We couldn’t save your response. Please try again.')}setDone(true);toast.success('Salamat! Your RSVP has been received.')}catch(err){setError(err instanceof Error?err.message:'Unable to connect. Please try again.')}finally{setBusy(false)}}
return <section id="rsvp" className="rsvp section"><div className="rsvp-intro"><span className="eyebrow">04 / TUGON</span><h2>There’s a place<br/>for you here.</h2><p>Our day wouldn’t be the same without you.<br/>Let us know if you can celebrate with us.</p><span className="deadline">PLEASE REPLY BY<br/><strong>{weddingData.deadline}</strong></span><Heart size={38} strokeWidth={.8}/></div>{done?<div className="rsvp-success" role="status"><Check size={40}/><h3>Salamat, from our hearts.</h3><p>{attendance==='attending'?'Your response is saved. We look forward to celebrating with you!':'Your response is saved. You’ll be with us in spirit.'}</p></div>:<form onSubmit={submit} className="rsvp-form"><label htmlFor="guest-name">Your full name <span>(as written on your invitation)</span></label><input id="guest-name" name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="First and last name"/><fieldset><legend>Will you be joining us?</legend><RadioGroup value={attendance} onValueChange={setAttendance} className="attendance-options"><label><RadioGroupItem value="attending"/> Joyfully accepts</label><label><RadioGroupItem value="declining"/> Regretfully declines</label></RadioGroup></fieldset>{attendance==='attending'&&<><label htmlFor="dietary">Dietary needs <span>(optional)</span></label><input id="dietary" name="dietary" maxLength={500} placeholder="Any allergies or dietary preferences?"/><label htmlFor="song">A song to get you dancing <span>(optional)</span></label><input id="song" name="song" maxLength={200} placeholder="Song title and artist"/></>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy?'Sending your response…':'Send my RSVP'}<ArrowUpRight size={17}/></button><p className="form-note">Your details will only be used to plan our wedding celebration.</p></form>}</section>}

