'use client';
import {useEffect,useRef,useState} from 'react';
import {Church,MailOpen,MapPinned,Martini,Utensils,Music2} from 'lucide-react';
import {ScrollNavigation} from './ScrollNavigation';
import {FAQList} from './InvitationInteractions';
import {InvitationVenues} from './InvitationVenues';
import {WeddingCountdown,WeddingDetails} from './WeddingSchedule';
import {Gallery} from './Gallery';
import {GuestMessages} from './GuestMessages';
import {AttireSection} from './AttireSection';
import {HouseholdRSVP} from './HouseholdRSVP';
import {BackgroundMusic} from './BackgroundMusic';
import {LogoPreloader} from './LogoPreloader';
export function WeddingInvitation(){const [responseCompleted,setResponseCompleted]=useState(false);const root=useRef<HTMLDivElement>(null);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.06});root.current?.querySelectorAll('.section-title,.couple-story,.venue,.timeline li,.tradition-grid article,.attire-grid article,.rsvp-panel').forEach(el=>{el.classList.add('reveal');observer.observe(el)});return()=>observer.disconnect()},[]);return <div ref={root} className="invitation-site"><a className="skip-link" href="#main">Skip to content</a>
<ScrollNavigation />
<LogoPreloader />
<BackgroundMusic />
<main id="main"><section id="home" className="hero"><div className="hero-title"><span className="lace left"></span><span className="lace right"></span><p className="eyebrow">Together with our families</p><h1 className="hero-names">Clive <span className="hero-amp">&amp;</span> Rubie</h1><p className="eyebrow hero-tagline">Sa bawat bukas, ikaw.</p><WeddingCountdown /></div><div className="hero-photo"><img fetchPriority="high" src="/invitation/hero-4487.webp" alt="Clive holding Rubie beneath a softly illuminated heritage arch" /><p>Two paths.<br />One beautiful<br />beginning.<span className="hero-rule" aria-hidden="true">❖</span></p></div><div className="hero-seal" aria-hidden="true"><img src="/invitation/monogram-new.png" alt="" /><span className="sprig seal-left"></span><span className="sprig seal-right"></span></div></section>
<WeddingDetails />
<section id="story" className="section rose story"><div className="container"><div className="section-title"><h2>Ang aming kwento</h2><p className="subtitle">A story still being written.</p></div><div className="couple-story"><article className="story-person story-clive"><div className="story-portrait"><div className="story-portrait-crop"><img src="/photos/gallery/portrait-4199.webp" alt="Clive seated beside a softly lit window" width="1333" height="2000" loading="lazy"/></div></div><blockquote><p>“Sa piling mo, ang bawat bukas ay tahanan.”</p><cite><span aria-hidden="true"/>Clive</cite></blockquote></article><article className="story-person story-rubie"><div className="story-portrait"><div className="story-portrait-crop"><img src="/photos/gallery/portrait-4041-updated.webp" alt="Rubie in her embroidered Filipiniana" width="1333" height="2000" loading="lazy"/></div></div><blockquote><p>“Sa bawat kailan, sino't saan<br/>Ikaw lamang ang kasagutan.”</p><cite><span aria-hidden="true"/>Rubie</cite></blockquote></article></div></div><span className="sprig story-sprig" aria-hidden="true"></span></section>
<Gallery />
<section id="programme" className="section programme"><span className="programme-floral floral-top" aria-hidden="true"/><span className="programme-floral floral-bottom" aria-hidden="true"/><div className="container programme-paper"><div className="section-title"><p className="programme-kicker">Our wedding day</p><h2>Order of celebration</h2><p className="programme-couple">Clive &amp; Rubie</p><p className="eyebrow">November 29, 2026 · Philippine time</p></div><ol className="timeline"><li><span className="timeline-mark"><Church size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Ceremony</h3><p className="programme-time">1:00 PM</p><p>Join us as we exchange our vows at St. James the Greater Church.</p></div></li><li><span className="timeline-mark"><Martini size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Cocktails</h3><p className="programme-time">4:00 PM</p><p>Enjoy drinks and conversation at Nato's Farm before the reception.</p></div></li><li><span className="timeline-mark"><Utensils size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Reception</h3><p className="programme-time">5:00 PM</p><p>Celebrate with dinner, heartfelt toasts, and memories together.</p></div></li><li><span className="timeline-mark"><Music2 size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Dancing</h3><p>Stay for the music and celebrate with us on the dance floor.</p></div></li></ol></div></section>
<InvitationVenues />
<section id="traditions" className="section traditions"><div className="container"><div className="section-title"><h2>Filipino traditions</h2><p className="eyebrow">Symbols of love and togetherness</p></div><div className="tradition-grid"><article><h3>Veil Ceremony</h3><p>A veil gathers the couple beneath one shelter of love.</p></article><article><h3>Cord Ceremony</h3><p>A figure-eight cord represents a lasting bond.</p></article><article><h3>Coin Ceremony (Arrhae)</h3><p>Thirteen coins symbolise blessings shared in a new home.</p></article><article><h3>Candle Ceremony</h3><p>Candlelight honours the joining of two families.</p></article></div></div></section>
<section id="colours" className="section colours"><div className="container"><div className="section-title"><h2>Our colours</h2><p className="eyebrow">A timeless palette for a brighter tomorrow.</p></div><div className="swatches"><div><i style={{background:"#B77D87"}}></i><span>Old rose</span></div><div><i style={{background:"#F3B8C7"}}></i><span>Blush</span></div><div><i style={{background:"#D2CED0"}}></i><span>Warm grey</span></div><div><i style={{background:"#9BA89A"}}></i><span>Sage</span></div><div><i style={{background:"#EDE8D0"}}></i><span>Beige</span></div></div></div></section>
<AttireSection />
<section id="faq" className="section faq"><div className="container"><div className="section-title"><h2>Common inquiries</h2><p className="eyebrow">Quick answers for a smoother celebration.</p></div><FAQList /></div></section>
<section id="reminders" className="section rose reminders"><div className="container"><div className="section-title"><h2>Kindly note</h2><p className="eyebrow">A few friendly reminders.</p></div><div className="reminder-grid"><article><span className="line-icon"><Church size={40} strokeWidth={1.6} aria-hidden="true"/></span><h3>During the ceremony</h3><p>Please arrive early, silence your phone, and keep cameras tucked away <strong>from the entourage processional through the end of the ceremony.</strong> Our photographers will capture the memories for everyone to enjoy.</p></article><article><span className="line-icon"><MailOpen size={40} strokeWidth={1.6} aria-hidden="true"/></span><h3>RSVP deadline</h3><p>Please respond by <strong className="rsvp-deadline-date">November 7, 2026</strong>.</p></article><article><span className="line-icon"><MapPinned size={40} strokeWidth={1.6} aria-hidden="true"/></span><h3>Getting there</h3><p>You may travel by private vehicle, taxi, or an available ride-hailing service. Use the venue directions above, allow extra travel time, and arrange your return ride in advance.</p></article></div></div></section>
<div className="invitation-closing"><span className="sprig closing-floral closing-floral-left" aria-hidden="true"/><span className="sprig closing-floral closing-floral-right" aria-hidden="true"/><section id="gifts" className="section gifts"><div className="container"><h2>Your presence is our present.</h2><p>Celebrating with you means the most.</p></div></section>
<section id="rsvp" className="rsvp-section"><HouseholdRSVP onCompletionChange={setResponseCompleted}/></section>
{responseCompleted&&<GuestMessages/>}</div>
</main><footer><div className="footer-logo"><span></span><img src="/invitation/footer-seal.svg" alt="Clive and Rubie monogram" /><span></span></div><p className="hashtag">#CliveFoundHisRubie</p><p className="eyebrow">Same places. More love to come.</p><p className="footer-credit">Made with love by Clive 💜</p></footer></div>}

