'use client';
import {useEffect,useRef} from 'react';
import {Church,MailOpen,MapPinned,Martini,Utensils,Music2} from 'lucide-react';
import {ScrollNavigation} from './ScrollNavigation';
import {StorySlideshow,FAQList} from './InvitationInteractions';
import {InvitationVenues} from './InvitationVenues';
import {WeddingCountdown,WeddingDetails} from './WeddingSchedule';
import {Gallery} from './Gallery';
import {AttireSection} from './AttireSection';
import {HouseholdRSVP} from './HouseholdRSVP';
import {BackgroundMusic} from './BackgroundMusic';
import {LogoPreloader} from './LogoPreloader';
function GoldDiamond(){return <svg className="gold-diamond" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="m12 1 4 4-4 4-4-4Zm0 14 4 4-4 4-4-4ZM1 12l4-4 4 4-4 4Zm14 0 4-4 4 4-4 4Zm-3-3 3 3-3 3-3-3Z"/></svg>}
export function WeddingInvitation(){const root=useRef<HTMLDivElement>(null);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.06});root.current?.querySelectorAll('.section-title,.story-layout,.venue,.timeline li,.tradition-grid article,.attire-grid article,.rsvp-panel').forEach(el=>{el.classList.add('reveal');observer.observe(el)});return()=>observer.disconnect()},[]);return <div ref={root} className="invitation-site"><a className="skip-link" href="#main">Skip to content</a>
<ScrollNavigation />
<LogoPreloader />
<BackgroundMusic />
<main id="main"><section id="home" className="hero"><div className="hero-title"><span className="lace left"></span><span className="lace right"></span><p className="eyebrow">Together with our families</p><h1 className="hero-names">Clive <span className="hero-amp">&amp;</span> Rubie</h1><p className="eyebrow">Sa bawat bukas, ikaw.</p><WeddingCountdown /><div className="ornament" aria-hidden="true"><GoldDiamond /></div></div><div className="hero-photo"><img fetchPriority="high" src="/invitation/hero.jpg" alt="Clive and Rubie beneath an illuminated heritage arch" /><p>Two paths.<br />One beautiful<br />beginning.<span className="hero-rule" aria-hidden="true">❖</span></p></div><div className="hero-seal" aria-hidden="true"><img src="/invitation/monogram-new.png" alt="" /><span className="sprig seal-left"></span><span className="sprig seal-right"></span></div></section>
<WeddingDetails />
<section id="story" className="section rose story"><div className="container"><div className="section-title"><h2>Ang aming kwento</h2><p className="subtitle">A story still being written.</p><div className="ornament" aria-hidden="true"><GoldDiamond /></div></div><div className="story-layout"><StorySlideshow /><div className="chapters"><article><GoldDiamond /><h3>Chapter one</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></article><article><GoldDiamond /><h3>Chapter two</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></article><article><GoldDiamond /><h3>Chapter three</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></article></div></div></div><span className="sprig story-sprig" aria-hidden="true"></span></section>
<InvitationVenues />
<section id="programme" className="section programme"><div className="container"><div className="section-title"><h2>Programme</h2><p className="eyebrow">November 29, 2026 · Philippine time</p></div><ol className="timeline"><li><span className="timeline-mark"><Church size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Ceremony</h3><p className="programme-time">1:00 PM</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p></div></li><li><span className="timeline-mark"><Martini size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Cocktails</h3><p className="programme-time">4:00 PM</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p></div></li><li><span className="timeline-mark"><Utensils size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Reception</h3><p className="programme-time">5:00 PM</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p></div></li><li><span className="timeline-mark"><Music2 size={24} strokeWidth={1.7} aria-hidden="true"/></span><div><h3>Dancing</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p></div></li></ol></div></section>
<section id="traditions" className="section traditions"><div className="container"><div className="section-title"><h2>Filipino traditions</h2><p className="eyebrow">Symbols of love and togetherness</p></div><div className="tradition-grid"><article><h3>Veil Ceremony</h3><p>A veil gathers the couple beneath one shelter of love.</p></article><article><h3>Cord Ceremony</h3><p>A figure-eight cord represents a lasting bond.</p></article><article><h3>Coin Ceremony (Arrhae)</h3><p>Thirteen coins symbolise blessings shared in a new home.</p></article><article><h3>Candle Ceremony</h3><p>Candlelight honours the joining of two families.</p></article></div><p className="confirmation">Ceremony details to be confirmed.</p></div></section>
<section id="colours" className="section colours"><div className="container"><div className="section-title"><h2>Our colours</h2><p className="eyebrow">A timeless palette for a brighter tomorrow.</p></div><div className="swatches"><div><i style={{background:"#B77D87"}}></i><span>Old rose</span></div><div><i style={{background:"#F3B8C7"}}></i><span>Blush</span></div><div><i style={{background:"#D2CED0"}}></i><span>Warm grey</span></div><div><i style={{background:"#9BA89A"}}></i><span>Sage</span></div><div><i style={{background:"#FFF9F3"}}></i><span>Ivory</span></div></div></div></section>
<AttireSection />
<Gallery />
<section id="faq" className="section faq"><div className="container"><div className="section-title"><h2>Common inquiries</h2><p className="eyebrow">Quick answers for a smoother celebration.</p></div><FAQList /></div></section>
<section id="reminders" className="section rose reminders"><div className="container"><div className="section-title"><h2>Kindly note</h2><p className="eyebrow">A few friendly reminders.</p></div><div className="reminder-grid"><article><span className="line-icon"><Church size={40} strokeWidth={1.6} aria-hidden="true"/></span><h3>During the ceremony</h3><p>Details to follow.</p></article><article><span className="line-icon"><MailOpen size={40} strokeWidth={1.6} aria-hidden="true"/></span><h3>RSVP deadline</h3><p>Details to follow.</p></article><article><span className="line-icon"><MapPinned size={40} strokeWidth={1.6} aria-hidden="true"/></span><h3>Getting there</h3><p>Details to follow.</p></article></div></div></section>
<section id="gifts" className="section gifts"><span className="sprig gift-left"></span><div className="container"><h2>Your presence is our present.</h2><p>Celebrating with you means the most.</p></div><span className="sprig gift-right"></span></section>
<section id="rsvp" className="rsvp-section"><HouseholdRSVP /></section>
</main><footer><div className="footer-logo"><span></span><img src="/invitation/monogram-new.png" alt="Clive and Rubie monogram" /><span></span></div><p className="hashtag">#CliveFoundHisRubie</p><p className="eyebrow">Same places. More love to come.</p><p className="footer-credit">Made with love by Clive 💜</p></footer></div>}

